EMMS/Models/EMdata.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace EMMS.Models
{
    public class EMdata
    {
        public int ID { get; set; }

        public string TerminalID { get; set; }

        [DisplayName("温度")]
        public double? Temperature { get; set; }

        [DisplayName("湿度")]
        public double? Humidity { get; set; }

        [DisplayName("PM2.5")]
        public int? Pm25 { get; set; }

        [DisplayName("亮度")]
        public int? Luminance { get; set; }

        [DisplayName("紫外线强度")]
        public int? UV { get; set; }

        [DisplayName("可燃气体浓度")]
        public int? GasIntensity { get; set; }

        [DisplayName("数据上传时间")]
        public DateTime Update { get; set; }

        public Terminal Terminal { get; set; }
    }
}

EMMS/Controllers/EMdataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMMS.Models;
using System.Data.Entity;

namespace EMMS.Controllers
{
    public class EMdataController : Controller
    {
        DB db = new DB();
        public ActionResult Index(int id=1,string terminal="EMMS001")
        {
            Bindddl();
            ViewBag.TerminalID = terminal;
            var result = db.EMdatas.Where(p=>p.TerminalID==terminal).Include(p=>p.Terminal).OrderBy(p=>p.Update);
            var bindColor = (IEnumerable<EMdata>)result;
            EMdata now = new EMdata();
            if (bindColor.LastOrDefault() != null)
            {
                now.Temperature = bindColor.LastOrDefault().Temperature;
                now.Pm25 = bindColor.LastOrDefault().Pm25;
                now.Luminance = bindColor.LastOrDefault().Luminance;
                now.Humidity = bindColor.LastOrDefault().Humidity;
                now.UV = bindColor.LastOrDefault().UV;
                now.GasIntensity = bindColor.LastOrDefault().GasIntensity;
                BindColor(now);
            }
            if (result.Count() == 0)
            {
                EMdata em = new EMdata();
                Terminal term = new Terminal();
                term.TerminalName = "无";
                term.TerminalAddr = "无";
                em.Terminal = term;
                em.UV = em.Pm25 = em.Luminance = em.GasIntensity = -1;
                em.Humidity = em.Temperature = -1;
                List<EMdata> emlst=new List<EMdata>();
                emlst.Add(em);
                return View(emlst);
            }
            return View(result);
        }

        public ActionResult Month(string terminal = "EMMS001")
        {
            Bindddl();

            DateTime Ago24 = DateTime.Now.AddDays(-30);

            var result = db.EMdatas.Where(p => p.TerminalID == terminal && p.Update >= Ago24).Include(p => p.Terminal).OrderBy(p => p.Update);
            var bindColor = (IEnumerable<EMdata>)result;
            double TemAvg = 0, HumiAvg = 0, Pm25Avg = 0, LuminAvg = 0, UVAvg = 0;
            int count = 0;
            foreach (var item in bindColor)
            {
                TemAvg += (double)item.Temperature;
                HumiAvg += (double)item.Humidity;
                Pm25Avg += (int)item.Pm25;
                LuminAvg += (int)item.Luminance;
                UVAvg += (int)item.UV;
                count++;
            }
            TemAvg /= count;
            HumiAvg /= count;
            Pm25Avg /= count;
            LuminAvg /= count;
            UVAvg /= count;
            ViewBag.TemAvg = TemAvg;
            ViewBag.HumiAvg = HumiAvg;
            ViewBag.Pm25Avg = Pm25Avg;
            ViewBag.LuminAvg = LuminAvg;
            ViewBag.UVAvg = UVAvg;
            ViewBag.TerminalID = terminal;
            EMdata now = new EMdata();
            if (bindColor.LastOrDefault() != null)
            {
                now.Temperature = bindColor.LastOrDefault().Temperature;
                now.Pm25 = bindColor.LastOrDefault().Pm25;
                now.Luminance = bindColor.LastOrDefault().Luminance;
                now.Humidity = bindColor.LastOrDefault().Humidity;
                now.UV = bindColor.LastOrDefault().UV;
                now.GasIntensity = bindColor.LastOrDefault().GasIntensity;
                BindColor(now);
            }
            return View(result);
        }

        public ActionResult Weeks(string terminal = "EMMS001")
        {
            Bindddl();

            DateTime Ago24 = DateTime.Now.AddDays(-7);

            var result = db.EMdatas.Where(p => p.TerminalID == terminal && p.Update>=Ago24).Include(p => p.Terminal).OrderBy(p => p.Update);
            var bindColor = (IEnumerable<EMdata>)result;
            double TemAvg = 0, HumiAvg = 0, Pm25Avg = 0, LuminAvg = 0, UVAvg = 0;
            int count=0;
            foreach (var item in bindColor)
            {
                TemAvg += (double)item.Temperature;
                HumiAvg += (double)item.Humidity;
                Pm25Avg += (int)item.Pm25;
                LuminAvg += (int)item.Luminance;
                UVAvg += (int)item.UV;
                count++;
            }
            TemAvg /= count;
            HumiAvg /= count;
            Pm25Avg /= count;
            LuminAvg /= count;
            UVAvg /= count;
            ViewBag.TemAvg = TemAvg;
            ViewBag.HumiAvg = HumiAvg;
            ViewBag.Pm25Avg = Pm25Avg;
            ViewBag.LuminAvg = LuminAvg;
            ViewBag.UVAvg = UVAvg;
            ViewBag.TerminalID = terminal;
            EMdata now = new EMdata();
            if (bindColor.LastOrDefault() != null)
            {
                now.Temperature = bindColor.LastOrDefault().Temperature;
                now.Pm25 = bindColor.LastOrDefault().Pm25;
                now.Luminance = bindColor.LastOrDefault().Luminance;
                now.Humidity = bindColor.LastOrDefault().Humidity;
                now.UV = bindColor.LastOrDefault().UV;
                now.GasIntensity = bindColor.LastOrDefault().GasIntensity;
                BindColor(now);
            }
            return View(result);
        }

        public ActionResult Hours24(string terminal = "EMMS001")
        {
            Bindddl();

            DateTime Ago24 = DateTime.Now.AddDays(-1);

            var result = db.EMdatas.Where(p => p.TerminalID == terminal && p.Update >= Ago24).Include(p => p.Terminal).OrderBy(p => p.Update);
            var bindColor = (IEnumerable<EMdata>)result;
            double TemAvg = 0, HumiAvg = 0, Pm25Avg = 0, LuminAvg = 0, UVAvg = 0;
            int count = 0;
            foreach (var item in bindColor)
            {
                TemAvg += (double)item.Temperature;
                HumiAvg += (double)item.Humidity;
                Pm25Avg += (int)item.Pm25;
                LuminAvg += (int)item.Luminance;
                UVAvg += (int)item.UV;
                count++;
            }
            TemAvg /= count;
            HumiAvg /= count;
            Pm25Avg /= count;
            LuminAvg /= count;
            UVAvg /= count;
            ViewBag.TemAvg = TemAvg;
            ViewBag.HumiAvg = HumiAvg;
            ViewBag.Pm25Avg = Pm25Avg;
            ViewBag.LuminAvg = LuminAvg;
            ViewBag.UVAvg = UVAvg;
            ViewBag.TerminalID = terminal;
            EMdata now = new EMdata();
            if (bindColor.LastOrDefault() != null)
            {
                now.Temperature = bindColor.LastOrDefault().Temperature;
                now.Pm25 = bindColor.LastOrDefault().Pm25;
                now.Luminance = bindColor.LastOrDefault().Luminance;
                now.Humidity = bindColor.LastOrDefault().Humidity;
                now.UV = bindColor.LastOrDefault().UV;
                now.GasIntensity = bindColor.LastOrDefault().GasIntensity;
                BindColor(now);
            }
            return View(result);
        }

        private void BindColor(EMdata now)
        {
            if (null != now)
            {
                if (now.Temperature < 0)
                {
                    ViewBag.TemColor1 = "#188eff";
                    ViewBag.TemColor2 = "blue";
                }
                else if (now.Temperature >= 0 && now.Temperature < 10)
                {
                    ViewBag.TemColor1 = "#39fb18";
                    ViewBag.TemColor2 = "green";
                }
                else if (now.Temperature >= 10 && now.Temperature < 20)
                {
                    ViewBag.TemColor1 = "#ffe718";
                    ViewBag.TemColor2 = "yellow";
                }
                else if (now.Temperature >= 20 && now.Temperature < 30)
                {
                    ViewBag.TemColor1 = "#398a18";
                    ViewBag.TemColor2 = "orange";
                }
                else if (now.Temperature >= 30)
                {
                    ViewBag.TemColor1 = "#ff2c18";
                    ViewBag.TemColor2 = "red";
                }

                if (now.Pm25 >= 0 && now.Pm25 < 75)
                {
                    ViewBag.Pm25Color1 = "P6";
                    ViewBag.Pm25Color2 = "#3BCA18";
                    ViewBag.Pm25Level = "优";
                }
                else if (now.Pm25 >= 75 && now.Pm25 < 150)
                {
                    ViewBag.Pm25Color1 = "P5";
                    ViewBag.Pm25Color2 = "#EEDC32";
                    ViewBag.Pm25Level = "良";
                }
                else if (now.Pm25 >= 150 && now.Pm25 < 300)
                {
                    ViewBag.Pm25Color1 = "P4";
                    ViewBag.Pm25Color2 = "#DCAD43";
                    ViewBag.Pm25Level = "轻度污染";
                }
                else if (now.Pm25 >= 300 && now.Pm25 < 1050)
                {
                    ViewBag.Pm25Color1 = "P3";
                    ViewBag.Pm25Color2 = "#F2401A";
                    ViewBag.Pm25Level = "中度污染";
                }
                else if (now.Pm25 >= 1050 && now.Pm25 < 3000)
                {
                    ViewBag.Pm25Color1 = "P2";
                    ViewBag.Pm25Color2 = "#BF0841";
                    ViewBag.Pm25Level = "重度污染";
                }
                else if (now.Pm25 >= 3000)
                { 
                    ViewBag.Pm25Color1 = "P1";
                    ViewBag.Pm25Color2 = "#9B0A4D";
                    ViewBag.Pm25Level = "严重污染";
                }

                if (now.Luminance >= 0 && now.Luminance < 5) ViewBag.LuminColor = "L5";
                else if (now.Luminance >= 5 && now.Luminance < 75) ViewBag.LuminColor = "L4";
                else if (now.Luminance >= 75 && now.Luminance < 750) ViewBag.LuminColor = "L3";
                else if (now.Luminance >= 750 && now.Luminance < 7500) ViewBag.LuminColor = "L2";
                else if (now.Luminance >= 7500) ViewBag.LuminColor = "L1";

EMMS/Views/EMdata/Hours24.cshtml
@{
    Layout = null;
}
@using EMMS.Models;
@using JQChart.Web.Mvc;
@model IEnumerable<EMdata>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>环境监测数据-24小时数据</title>
    <link href="/Content/Reset.css" rel="stylesheet" />
    <link href="/Content/Site.css" rel="stylesheet" />
    <link href="/Content/jquery.jqChart.css" rel="stylesheet" />
    <link href="/Content/jquery.jqRangeSlider.css" rel="stylesheet" />
    <link href="~/Content/themes/smoothness/jquery-ui-1.8.21.css" rel="stylesheet" />

    <script src="/Scripts/jquery-1.9.1.js"></script>
    <script src="/Scripts/jquery.jqChart.min.js"></script>
    <script src="/Scripts/jquery.jqRangeSlider.min.js"></script>
    <!--[if IE]><script lang="javascript" type="text/javascript" src="/Scripts/excanvas.js"></script><![endif]-->

    <script>
        function request(paras) {
            var url = location.href;
            var paraString = url.substring(url.indexOf("?") + 1, url.length).split("&");
            var paraObj = {}
            for (i = 0; j = paraString[i]; i++) {
                paraObj[j.substring(0, j.indexOf("=")).toLowerCase()] = j.substring(j.indexOf("=") + 1, j.length);
            }
            var returnValue = paraObj[paras.toLowerCase()];
            if (typeof (returnValue) == "undefined") {
                return "";
            } else {
                return returnValue;
            }
        }

        $(document).ready(function () {
            $('#sensorSel select').val(request("terminal"));
            $('#sensorSel select').change(function () {
                location.href = '/emdata/Hours24' + "?terminal=" + $(this).children('option:selected').val();
            })
        })
    </script>
</head>
<body>
    <div id="nav" class="clear-fix">
        <ul class="clear-fix">
            <li class="index">
                @*<a href="Index.html">首页</a>*@
                @Html.ActionLink("首页", "Index", "EMdata", new { terminal=ViewBag.TerminalID },null)
            </li>
            <li>
                @*<a href="24Hour.html">24小时</a>*@
                @Html.ActionLink("24小时","Hours24","EMdata", new { terminal=ViewBag.TerminalID },null)
            </li>
            <li>
                @*<a href="Week.html">一周</a>*@
                @Html.ActionLink("一周","Weeks","EMdata", new { terminal=ViewBag.TerminalID },null)
            </li>
            <li>
                @*<a href="Month.html">一个月</a>*@
                @Html.ActionLink("一个月","Month","EMdata", new { terminal=ViewBag.TerminalID },null)
            </li>
        </ul>
        <div id="sensorSel">
            <p>传感器选择</p>
            @Html.DropDownList("TerminalChoice", (IEnumerable<SelectListItem>)ViewBag.TerList)
        </div>
        <div id="bqsm">
            Leroy Copyright©2013
        </div>
    </div>

    <div id="main">
        <div class="mulavg clear-fix" id="avg">
            <p class="title">24小时均值</p>
            <div class="datamul">
                <ul>
                    <li class="@(ViewBag.Pm25Color1)">
                        <span>@ViewBag.TemAvg.ToString("0.0")℃</span>
                        <p>温度</p>
                    </li>
                    <li class="@ViewBag.Pm25Color1">
                        <span>@ViewBag.Pm25Avg.ToString("0.0")</span>
                        <p>PM2.5</p>
                    </li>
                    <li class="@ViewBag.HumiColor">
                        <span>@ViewBag.HumiAvg.ToString("0.0")%</span>
                        <p>湿度</p>
                    </li>
                    <li class="@ViewBag.LuminColor">
                        <span>@ViewBag.LuminAvg.ToString("0.0")</span>
                        <p>亮度</p>
                    </li>
                    <li class="@ViewBag.UVColor">
                        <span>@ViewBag.UVAvg.ToString("0.0")</span>
                        <p>紫外线</p>
                    </li>
                </ul>
            </div>
        </div>

        <div class="mulavg  clear-fix">
            <p class="title">PM2.5</p>
            <div class="plot">
                <div id="pm25Chart" style="width: 780px; height: 230px;">
                     @(Html.JQChart()
                .Chart(Model)
                .ID("pm25")
                .Width(780)
                .Height(230)
                .Title("PM2.5")
                .Legend(el =>el.Title("Legend"))
                .Border(border => border.StrokeStyle("#6ba851"))
                .Background(background => background.LinearGradient(0, 0, 0, 1).ColorStops(stop =>
                {
                    stop.Add(0, "#d2e6c9");
                    stop.Add(1, "white");
                }))
                .Tooltips(tooltips => tooltips.TooltipsType(TooltipsType.Shared))
                .Crosshairs(el => el.Enabled(true).VerticalLine(line => line.StrokeStyle("#cc0a0c")).HorizontalLine(false))
                .Animation(TimeSpan.FromSeconds(2))
                .Shadows(true)
                .Axes(axis => axis.DateTimeAxis(Location.Bottom).ZoomEnabled(true))
                .Series(series => series.Line().Title("PM2.5").XValues(el => el.Update).YValues(el => el.Pm25).Markers(false))
                .Render() 
          )
                </div>
            </div>
        </div>
        <div class="mulavg  clear-fix">
            <p class="title">温度</p>
            <div class="plot">
                <div id="temChart" style="width: 780px; height: 230px;">
                     @(Html.JQChart()
                .Chart(Model)
                .ID("Tem")
                .Width(780)
                .Height(230)
                .Title("温度")
                .Legend(el =>el.Title("Legend"))
                .Border(border => border.StrokeStyle("#6ba851"))
                .Background(background => background.LinearGradient(0, 0, 0, 1).ColorStops(stop =>
                {
                    stop.Add(0, "#d2e6c9");
                    stop.Add(1, "white");
                }))
                .Tooltips(tooltips => tooltips.TooltipsType(TooltipsType.Shared))
                .Crosshairs(el => el.Enabled(true).VerticalLine(line => line.StrokeStyle("#cc0a0c")).HorizontalLine(false))
                .Animation(TimeSpan.FromSeconds(2))
                .Shadows(true)
                .Axes(axis => axis.DateTimeAxis(Location.Bottom)
                                  .ZoomEnabled(true))
                .Series(series => series.Line()
                                        .Title("温度")
                                        .XValues(el => el.Update)
                                        .YValues(el => el.Temperature)
                                        .Markers(false))
                .Render() 
          )
                </div>
            </div>
        </div>
        <div class="mulavg  clear-fix">
            <p class="title">湿度</p>
            <div class="plot">
                <div id="humiChart" style="width: 780px; height: 230px;">
                    @(Html.JQChart()
                .Chart(Model)
                .ID("Humi")
                .Width(780)
                .Height(230)
                .Title("湿度")
                .Legend(el =>el.Title("Legend"))
                .Border(border => border.StrokeStyle("#6ba851"))
                .Background(background => background.LinearGradient(0, 0, 0, 1).ColorStops(stop =>
                {
                    stop.Add(0, "#d2e6c9");
                    stop.Add(1, "white");
                }))
                .Tooltips(tooltips => tooltips.TooltipsType(TooltipsType.Shared))
                .Crosshairs(el => el.Enabled(true).VerticalLine(line => line.StrokeStyle("#cc0a0c")).HorizontalLine(false))
                .Animation(TimeSpan.FromSeconds(2))
                .Shadows(true)
                .Axes(axis =>
                    {
                        axis.DateTimeAxis(Location.Bottom)
                            .ZoomEnabled(true);
                    }
                )
                .Series(series =>
                    {
                        series.Line()
                              .Title("湿度")
                              .XValues(el => el.Update)
                              .YValues(el => el.Humidity)
                              .Markers(false);
                    }
                )
                .Render() 
          )
                </div>
            </div>
        </div>
        <div class="mulavg  clear-fix">
            <p class="title">亮度</p>
            <div class="plot">
                <div id="lightChart" style="width: 780px; height: 230px;">
                    @(Html.JQChart()
                .Chart(Model)
                .ID("Lumin")
                .Width(780)
                .Height(230)
                .Title("亮度")
                .Legend(el =>el.Title("Legend"))
                .Border(border => border.StrokeStyle("#6ba851"))
                .Background(background => background.LinearGradient(0, 0, 0, 1).ColorStops(stop =>
                {
                    stop.Add(0, "#d2e6c9");
                    stop.Add(1, "white");
                }))
                .Tooltips(tooltips => tooltips.TooltipsType(TooltipsType.Shared))
                .Crosshairs(el => el.Enabled(true).VerticalLine(line => line.StrokeStyle("#cc0a0c")).HorizontalLine(false))
                .Animation(TimeSpan.FromSeconds(2))
                .Shadows(true)
                .Axes(axis =>
                    {
                        axis.DateTimeAxis(Location.Bottom)
                            .ZoomEnabled(true);
                    }
                )
                .Series(series =>
                    {
                        series.Line()
                              .Title("亮度")
                              .XValues(el => el.Update)
                              .YValues(el => el.Luminance)
                              .Markers(false);
                    }
                )
                .Render() 
          )
                </div>
            </div>
        </div>
        <div class="mulavg  clear-fix">
            <p class="title">紫外强度</p>
            <div class="plot">
                <div id="uvChart" style="width: 780px; height: 230px;">
                    @(Html.JQChart()
                .Chart(Model)
                .ID("Uv")
                .Width(780)
                .Height(230)
                .Title("紫外线强度")
                .Legend(el =>el.Title("Legend"))
                .Border(border => border.StrokeStyle("#6ba851"))
                .Background(background => background.LinearGradient(0, 0, 0, 1).ColorStops(stop =>
                {
                    stop.Add(0, "#d2e6c9");
                    stop.Add(1, "white");
                }))
                .Tooltips(tooltips => tooltips.TooltipsType(TooltipsType.Shared))
                .Crosshairs(el => el.Enabled(true).VerticalLine(line => line.StrokeStyle("#cc0a0c")).HorizontalLine(false))
                .Animation(TimeSpan.FromSeconds(2))
                .Shadows(true)
                .Axes(axis =>
                    {
                        axis.DateTimeAxis(Location.Bottom)
                            .ZoomEnabled(true);
                    }
                )
                .Series(series =>
                    {
                        series.Line()
                              .Title("紫外线强度")
                              .XValues(el => el.Update)
                              .YValues(el => el.UV)
                              .Markers(false);
                    }
                )
                .Render() 
          )
                </div>
            </div>
        </div>
    </div>

    <script lang="javascript" type="text/javascript">
        function bindChartStyle(chartID) {
            $(chatID).bind('tooltipFormat', function (e, data) {

                var date = data.chart.stringFormat(data.x, "ddd, mmm dS, yyyy");

                var tooltip = '<b>' + date + '</b></br>' +
                      '<span style="color:' + data.series.fillStyle + '">' + data.series.title + ': </span>' +
                      '<b>' + data.y + '</b></br>';

                return tooltip;
            });
        }

        $(document).ready(function () {
            bindChartStyle("#pm25");
            bindChartStyle("#Tem");
            bindChartStyle("#Humi");
            bindChartStyle("#Lumin");
            bindChartStyle("#Uv");
        });
    </script>
</body>
</html>